command_timeout = 1000

[nodejs]
detect_extensions = []

[cmake]
disabled = true

# With warnings disabled, this trick still shows the difference between if the git status is clean, or the module timed out
# A time out shows nothing, while a clean slate shows the branch symbol
[git_branch]
symbol = ''
[git_status]
stashed = ''
up_to_date = '[](bold purple) '
ahead = '[](bold purple) [(\($count ahead\) )](bold red)'
behind = '[](bold purple) [(\($count behind\) )](bold red)'
diverged = '[](bold purple) [(\($ahead_count ahead , $behind_count behind\) )](bold red)'
format = '($ahead_behind[$all_status](bold red) )'


[directory]
use_logical_path = false
truncate_to_repo = false
truncation_length = 10
before_repo_root_style = 'cyan'
repo_root_style = 'bold cyan'
style = 'bold cyan'



