command_timeout = 1000

[nodejs]
detect_extensions = []

[cmake]
disabled = true

[git_status]
stashed = ""

[directory]
use_logical_path = false
truncate_to_repo = false
truncation_length = 10
before_repo_root_style = 'cyan'
repo_root_style = 'bold cyan'
style = 'bold cyan'



