[manager]
prepend_keymap = [
	{ on = '<A-q>', run = 'quit --no-cwd-file' },
	{ on = '<C-q>', run = 'close' },
    
	{ on = '<C-o>', run = 'back', desc = 'Go back to the previous directory' },
	{ on = '<C-i>', run = 'forward', desc = 'Go forward to the next directory' },
	{ on = '<C-c>', run = 'escape --search', desc = 'Cancel the ongoing search' },
  
	{ on = '<C-c>', run = 'nop' },
	{ on = 'H', run = 'nop' },
	{ on = 'L', run = 'nop' },
	{ on = '<C-s>', run = 'nop' },

	{ on = "s", run = "search fd --args -p", desc = "Search files by name using fd" },
	{ on = "v", run = "plugin visual", desc = "Toggle visual mode" },

	{ on = "<A-o>", run = "shell --orphan %1", desc = "OS open" },
]
