[mgr]
prepend_keymap = [
	{ on = '<A-q>', run = 'quit --no-cwd-file' },
	{ on = '<C-q>', run = 'close' },
    
	{ on = '<C-o>', run = 'back', desc = 'Go back to the previous directory' },
	{ on = '<C-i>', run = 'forward', desc = 'Go forward to the next directory' },
	{ on = '<C-c>', run = 'escape --search', desc = 'Cancel the ongoing search' },
  
	{ on = 'H', run = 'nop' },
	{ on = 'L', run = 'nop' },
	{ on = '<C-s>', run = 'nop' },

	{ on = "s", run = "search --via=fd --args='-p --no-ignore'", desc = "Search files by pattern using fd (also gitignored files)" },
	{ on = "<A-s>", run = 'search --via=fd', desc = "Search(tracked) files" },
	{ on = "v", run = "plugin visual", desc = "Toggle visual mode" },

	{ on = "<A-o>", run = "shell --orphan %1", desc = "OS open" },

	{ on = [ "g", "d" ],       run = "cd ~/Desktop",   desc = "Go ~/Desktop" },
]

