theme = "ansi16"

[editor]
line-number = "relative"
soft-wrap.enable = true
shell = ["nu", "--stdin", "-c"]

[editor.indent-guides]
render = true
skip-levels = 1

[editor.whitespace.render]
#space = "all"
ndsp = "all"
tab = "all"
#newline = "all"

#[editor.whitespace.render]
#space = "none"
#nbsp = "none"
#tab = "none"
#newline = "none"

#[editor.whitespace.characters]
#space = "·"
#nbsp = "⍽"
#tab = "→"
#newline = "⏎"
#tabpad = "·"

#[editor.cursor-shape]
#insert = "bar"
#normal = "block"
#select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
"," = "repeat_last_motion"
"S-esc" = "keep_primary_selection"
"C-s" = ["save_selection", ":w"]
"A-s" = "save_selection"
"C-q" = ":quit"
"C-/" = "toggle_comments"
"C-6" = "goto_last_accessed_file"
"H" = ["collapse_selection", "select_mode", "goto_line_start", "exit_select_mode"]
"L" = ["collapse_selection", "select_mode", "goto_line_end", "exit_select_mode"]
"X" = "extend_to_line_bounds"
"x" = ["extend_to_line_bounds", "trim_selections"]

"F12" = "goto_definition"
"S-F12" = "goto_reference"

[keys.normal.space]
F = "file_picker_in_current_buffer_directory"

