theme = "neo-ansi"

[editor]
line-number = "relative"
soft-wrap.enable = true
shell = ["nu", "--stdin", "-c"]
auto-pairs = false

[editor.indent-guides]
render = true
skip-levels = 1

[editor.whitespace.render]
ndsp = "all"
tab = "all"
#space = "all"
#newline = "all"

#[editor.whitespace.render]
#space = "none"
#nbsp = "none"
#tab = "none"
#newline = "none"

#[editor.whitespace.characters]
#space = "·"
#nbsp = "⍽"
#tab = "→"
#newline = "⏎"
#tabpad = "·"

#[editor.cursor-shape]
#insert = "bar"
#normal = "block"
#select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
"," = "repeat_last_motion"
"S-esc" = "keep_primary_selection"
"C-s" = ["save_selection", ":w"]
"A-s" = "save_selection"
"C-q" = ":quit"
"C-/" = "toggle_comments"
"C-6" = "goto_last_accessed_file"
"X" = "extend_to_line_bounds"
"x" = ["extend_to_line_bounds", "trim_selections"]

"ret" = ["open_below", "normal_mode"]
"H" = ["collapse_selection", "select_mode", "goto_line_start", "exit_select_mode"]
"L" = ["collapse_selection", "select_mode", "goto_line_end", "exit_select_mode"]

"F12" = "goto_definition"
"S-F12" = "goto_reference"

[keys.select]
"," = "repeat_last_motion"
"S-esc" = "keep_primary_selection"
"C-s" = ["save_selection", ":w"]
"A-s" = "save_selection"
"C-q" = ":quit"
"C-/" = "toggle_comments"
"C-6" = "goto_last_accessed_file"
"X" = "extend_to_line_bounds"
"x" = ["extend_to_line_bounds", "trim_selections"]

"H" = ["goto_line_start"]
"L" = ["goto_line_end"]

[keys.normal.space]
F = "file_picker_in_current_buffer_directory"

e = """
:sh echo `echo $':open (broot)\r' | wezterm cli send-text --pane-id (wezterm cli get-pane-direction left); exit\r` 
  | wezterm cli send-text --pane-id (wezterm cli split-pane --right --percent 33) --no-paste
"""
o = ":sh bash hx-wezterm.sh open"
r = ":sh bash hx-wezterm.sh run"
#b = ":sh bash hx-wezterm.sh blame"
#f = ":sh bash hx-wezterm.sh fzf"
#g = ":sh bash hx-wezterm.sh lazygit"
#s = ":sh bash hx-wezterm.sh test_single"
#t = ":sh bash hx-wezterm.sh test_all"