[[language]]
name = "markdown"
# text-width = 100
soft-wrap = { enable = true, wrap-at-text-width = false }

# The indent to use. Has sub keys unit (the text inserted into the document when indenting; usually set to N spaces or "\t" for tabs) and tab-width (the number of spaces rendered for a tab)
indent = { tab-width = 4, unit = "  " }

formatter = { command = 'sed', args = ['-b', 's/[ \t]*(\r?)$/\1/'] }


[[language]]
name = "tsv"
scope = "source.tsv"
file-types = ["tsv"]
roots = []
soft-wrap = { enable = false, wrap-at-text-width = false }
indent = { tab-width = 28, unit = "\t" }

[[language]]
name = "unison"
scope = "source.unison"
injection-regex = "unison"
file-types = ["u"]
shebangs = []
roots = []
auto-format = false
comment-token = "--"
indent = { tab-width = 2, unit = "  " }
language-servers = [ "ucm" ]

[[language]]
name = "sql"
formatter = { command = "sqlformat", args = ["--reindent", "--indent_width", "2", "--keywords", "upper", "--identifiers", "lower", "-"] }

[[language]]
name = "c-sharp"
auto-format = false
language-servers = [ "omnisharp" ]

[language-server.omnisharp]
# relevant defaults:
# csharp-ls = { command = "csharp-ls" }
# omnisharp = { command = "OmniSharp", args = [ "--languageserver" ] }
# omnisharp = { command = "OmniSharp", args = [ "--languageserver" ], timeout = 30 }
command = "dotnet"
args = [ "C:/Program Files/OmniSharp/OmniSharp.dll", "--languageserver" ]
timeout = 30

[language-server.ucm]
command = "ncat"
args = ["localhost", "5757"]

[[language]]
name = "xml"
formatter = { command = "tidy", args = ["-q", "-xml", "--show-errors", "0", "--show-warnings", "0", "--force-output", "--indent", "auto",  "--vertical-space", "yes", "--tidy-mark", "no", "-wrap", "120"] }
