[metadata]
aliases = []
author = 'chtenb'
name = 'Noctis Lux'

# Noctis Lux Ansi16
[colors]
foreground = "#005661"
background = "#fef8ec"
cursor_bg = "#005661"
cursor_border = "#005661"
cursor_fg = "#ffffff"
selection_bg = "#cfe7f0"
selection_fg = "#005661"

ansi = [ "#8ca6a6" ,"#e64100" ,"#00b368" ,"#fa8900" ,"#0095a8" ,"#ff5792" ,"#00bdd6" ,"#005661" ]
brights = [ "#8ca6a6" ,"#e5164a" ,"#00b368" ,"#b3694d" ,"#0094f0" ,"#ff5792" ,"#00bdd6" ,"#004d57" ]

# [colors.tab_bar]
# background = "e8e8e8",

# [colors.tab_bar.active_tab]
# fg_color = "#101010",
# bg_color = "#e8e8e8",

# [colors.tab_bar.inactive_tab]
# fg_color = "#808080",
# bg_color = "#e8e8e8",

# [colors.tab_bar.new_tab]
# fg_color = "#101010",
# bg_color = "#e8e8e8",

[colors.indexed] 
# background colors for git diffs
52 = "#fbdada" # red
88 = "#f6b6b6" # red emph
22 = "#d6ffd6" # green
28 = "#adffad" # green emph
53 = "#feecf7" # purple
17 = "#e5dff6" # blue
23 = "#d8fdf6" # cyan
58 = "#f4ffe0" # yellow

# Colors 232-255 are UX colors

# bg
232 = "#f8f1e0" # inactive background
233 = "#f1e7c9" # inactive overlay background
234 = "#efe9d5" # overlay background
235 = "#f1e7c9" # inactive overlay title bar
236 = "#e3ded3" # overlay title bar
237 = "#efebdf" # inactive main title bar
238 = "#efe9d5" # main title bar
239 = "#d8eef1" # special highlight
240 = "#daedeb" # inactive selection
241 = "#daedeb" # active selection
242 = "#d6f3fa" # inactive primary selection
243 = "#d6f3fa" # active primary selection
# fg
244 = "#707070" # rulers
245 = "#606060" # divider level 2
246 = "#585858" # divider level 1
247 = "#505050" #
248 = "#484848" # low intensity accent 2
249 = "#404040" #
250 = "#383838" # high intensity
251 = "#303030" #
252 = "#282828" # high intensity accent 1
253 = "#202020" #
254 = "#181818" # high intensity accent 2
255 = "#101010" #


[colors.tab_bar]
background = "#131a24"
inactive_tab_edge = "#131a24"
inactive_tab_edge_hover = "#212e3f"

[colors.tab_bar.active_tab]
bg_color = "#71839b"
fg_color = "#192330"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#212e3f"
fg_color = "#aeafb0"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#29394f"
fg_color = "#cdcecf"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#192330"
fg_color = "#aeafb0"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#29394f"
fg_color = "#cdcecf"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"
