# Synthwave Material Ansi 16
[colors]
foreground = "#cccccc"
background = "#262335"
cursor_bg = "#ffffff"
cursor_border = "#ffffff"
cursor_fg = "black"
selection_fg = "#cccccc"
selection_bg = "#333041"

ansi = ['#676e95' ,'#f07178' ,'#c3e88d' ,'#ffcb6b' ,'#94afeb' ,'#c792ea' ,'#b9dedf' ,'#b4b8d0']
brights = ['#676e95' ,'#ff5370' ,'#87de97' ,'#f78c6c' ,'#b9dedf' ,'#c792ea' ,'#91f5f8' ,'#dddddd']


[colors.indexed] 
52 = "#330f0f" # minus
88 = "#4f1917" # minus emph
22 = "#0e2f19" # plus
28 = "#174525" # plus emph
53 = "#330f29" # purple
17 = "#271344" # blue
23 = "#0d3531" # cyan
58 = "#222f14" # yellow
