
# This configuration file lets you
# - define new commands
# - change the shortcut or triggering keys of built-in verbs
# - change the colors
# - set default values for flags
# - set special behaviors on specific paths
# - and more...
# Configuration documentation is available at
#     https://dystroy.org/broot

# Default flags
# You can set up flags you want broot to start with by
# default, for example `default_flags="ihp"` if you usually want
# to see hidden and gitignored files and the permissions (then
# if you don't want the hidden files you can launch `br -H`)
# A popular flag is the `g` one which displays git related info.
default_flags = "gpi"

# Date/Time format
# If you want to change the format for date/time, uncomment the
# following line and change it according to
# https://docs.rs/chrono/0.4.11/chrono/format/strftime/index.html
# date_time_format = "%Y/%m/%d %R"

# uncomment to activate modal mode
# (you really should read https://dystroy.org/broot/modal/
# before as it may not suit everybody even among vim users)
# modal = true

# Whether to mark the selected line with a triangle
show_selection_mark = true

# Column order
# cols_order, if specified, must be a permutation of the following
# array. You should keep the name column at the end as it has a
# variable length.
# cols_order = ["mark", "git", "size", "permission", "date", "count", "branch", "name"]

# True Colors
# If this parameter isn't set, broot tries to automatically
# determine whether true colors (24 bits) are available.
# As this process is unreliable, you may uncomment this setting
# and set it to false or true if you notice the colors in
# previewed images are too off.
# true_colors = false

# Icons
# If you want to display icons in broot, uncomment this line
# (see https://dystroy.org/broot/icons for installation and
# troubleshooting)
# icon_theme = "vscode"

# Quit on last cancel
# You can usually cancel the last state change on escape.
# If you want the escape key to quit broot when there's nothing
# to cancel (for example when you just opened broot), uncomment
# this parameter
# quit_on_last_cancel = true

# Max file size for content search
# Bigger files are ignored when searching their content. You
# can specify this size either in ISO units (eg 5GB) or in
# the old binary units (eg 44Kib)
content_search_max_file_size = "10MB"

# Max Panels Count
# Change this if you sometimes want to have more than 2 panels
# open
# max_panels_count = 2

# Special paths
[special_paths]
"/media" = "no-enter" # comment it if desired
# "/media/slow-backup-disk" = "no-enter"
# "/home/dys/useless" = "hide"
# "/home/dys/my-link-I-want-to-explore" = "enter"

# Search modes
# This mapping may be modified. You may want to dedicate the
# empty prefix (the one which doesn't need a '/') to the
# search mode you use most often. The example below makes it
# easy to search on name rather than on the subpath.
# More information on
#  https://dystroy.org/broot/input/#the-filtering-pattern
# [search_modes]
# "<empty>" = "fuzzy name"
# "/" = "regex name"

# File Extension Colors
# uncomment and modify the next section if you want to color
# file name depending on their extension
# [ext_colors]
# png = "rgb(255, 128, 75)"
# rs = "yellow"

# Imports
# While it's possible to have all configuration in one file,
# it's more convenient to split it in several ones.
# Importing also allows to set a condition on the terminal's
# color, which makes it possible to have a different skin 
# chosen when your terminal has a light background and when
# it has a light one.
[[imports]]
file = "verbs.toml"

[[imports]]
luma = ["dark", "unknown", "light"]
file = "skins/neo-ansi.toml"
