
# This file contains the verb definitions for broot
# Doc at https://dystroy.org/broot/verbs/

[[verbs]]
# A standard recommended command for editing files
invocation = "edit"
#keys = ["Right"]
shortcut = "e"
execution = "$EDITOR {file}:{line}"
apply_to = "file"
leave_broot = false

[[verbs]]
# Unbind annoying shortcut
internal = ":close_panel_cancel"
keys = []

[[verbs]]
internal = ":input_del_word_left"
keys = ["ctrl-w"]

[[verbs]]
internal = ":back"
keys = ["ctrl-o"]

[[verbs]]
# print path and exit broot
invocation = "print_path"
keys = ["enter"]
shortcut = "pp"
apply_to = "file"
leave_broot = true
internal = ":print_path"

[[verbs]]
# Example 1: launching `tail -n` on the selected file (leaving broot)
name = "tail_lines"
invocation = "tl {lines_count}"
execution = "tail -f -n {lines_count} {file}"

[[verbs]]
# Example 2: creating a new file without leaving broot
name = "touch"
invocation = "touch {new_file}"
execution = "touch {directory}/{new_file}"
leave_broot = false

[[verbs]]
invocation = "create {subpath}"
execution = "$EDITOR {directory}/{subpath}"
leave_broot = false

[[verbs]]
invocation = "git_diff"
shortcut = "gd"
leave_broot = false
execution = "git difftool -y {file}"

[[verbs]]
invocation = "backup {version}"
key = "ctrl-b"
leave_broot = false
auto_exec = false
execution = "cp -r {file} {parent}/{file-stem}-{version}{file-dot-extension}"

[[verbs]]
invocation = "terminal"
key = "ctrl-t"
execution = "$SHELL"
set_working_dir = true
leave_broot = false

[[verbs]]
invocation = "line_up"
key = "ctrl-p"
internal = ":line_up"

[[verbs]]
invocation = "line_down"
key = "ctrl-n"
internal = ":line_down"

# ... Continue for other verb definitions ...
