# Author: chtenb <ctenbrinke@gmail.com>
inherits = "ansi16-syntax"

"ui.background" = { } # 
"ui.background.separator" = { } # Picker separator below input line
"ui.cursor" = { modifiers = ["reversed"] } # 
#"ui.cursor.normal" = { } # 
#"ui.cursor.insert" = { } # 
#"ui.cursor.select" = { } # 
#"ui.cursor.match" = { } # Matching bracket etc.
#"ui.cursor.primary" = { } # Cursor with primary selection
#"ui.cursor.primary.normal" = { } # 
#"ui.cursor.primary.insert" = { } # 
#"ui.cursor.primary.select" = { } # 
"ui.debug.breakpoint" = { fg = "red" } # Breakpoint indicator, found in the gutter
"ui.debug.active" = { fg = "red", bg = "yellow" } # Indicator for the line at which debugging execution is paused at, found in the gutter
#"ui.gutter" = { } # Gutter
#"ui.gutter.selected" = { } # Gutter for the line the cursor is on
#"ui.highlight.frameline" = { } # Line at which debugging execution is paused at
"ui.linenr" = { fg = "gray" } # Line numbers
"ui.linenr.selected" = { fg = "white" } # Line number for the line the cursor is on
"ui.statusline" = { bg = "black" } # Statusline
#"ui.statusline.inactive" = { } # Statusline (unfocused document)
#"ui.statusline.normal" = { } # Statusline mode during normal mode (only if editor.color-modes is enabled)
#"ui.statusline.insert" = { } # Statusline mode during insert mode (only if editor.color-modes is enabled)
#"ui.statusline.select" = { } # Statusline mode during select mode (only if editor.color-modes is enabled)
#"ui.statusline.separator" = { } # Separator character in statusline
"ui.popup" = { fg = "white", bg = "black" } # Documentation popups (e.g. Space + k)
#"ui.popup.info" = { fg = "white", bg = "black" } # Prompt for multiple key options
"ui.window" = { fg = "black" } # Borderlines separating splits
"ui.help" = { bg = "black" } # Description box for commands
"ui.text" = { } # Command prompts, popup text, etc.
#"ui.text.focus" = { } # 
#"ui.text.inactive" = { } # Same as ui.text but when the text is inactive (e.g. suggestions)
#"ui.text.info" = { } # The key: command text in ui.popup.info boxes
"ui.virtual.ruler" = { } # Ruler columns (see the editor.rulers config)
"ui.virtual.whitespace" = { fg = "black" } # Visible whitespace characters
"ui.virtual.indent-guide" = { fg = "black" } # Vertical indent width guides
#"ui.virtual.inlay-hint" = { } # Default style for inlay hints of all kinds
#"ui.virtual.inlay-hint.parameter" = { } # Style for inlay hints of kind parameter (LSPs are not required to set a kind)
#"ui.virtual.inlay-hint.type" = { } # Style for inlay hints of kind type (LSPs are not required to set a kind)
"ui.virtual.wrap" = { fg = "black" } # Soft-wrap indicator (see the editor.soft-wrap config)
"ui.menu" = { bg = "black" } # Code and command completion menus
"ui.menu.selected" = { bg = "gray" } # Selected autocomplete item
"ui.menu.scroll" = { bg = "light-gray" } # fg sets thumb color, bg sets track color of scrollbar
"ui.selection" = { fg = "black", modifiers = ["reversed"] } # For selections in the editing area
"ui.selection.primary" = { fg = "black", modifiers = ["reversed", "underline"] } # 
"ui.highlight" = { fg = "red" } # Highlighted lines in the picker preview
#"ui.cursorline.primary" = { } # The line of the primary cursor (if cursorline is enabled)
#"ui.cursorline.secondary" = { } # The lines of any other cursors (if cursorline is enabled)
#"ui.cursorcolumn.primary" = { } # The column of the primary cursor (if cursorcolumn is enabled)
#"ui.cursorcolumn.secondary" = { } # The columns of any other cursors (if cursorcolumn is enabled)
"warning" = { fg = "yellow" } # Diagnostics warning (gutter)
"error" = { fg = "red" } # Diagnostics error (gutter)
"info" = { fg = "blue" } # Diagnostics info (gutter)
"hint" = { fg = "green" } # Diagnostics hint (gutter)
"diagnostic" = { bg = "grey" } # Diagnostics fallback style (editing area)
#"diagnostic.hint" = { } # Diagnostics hint (editing area)
#"diagnostic.info" = { } # Diagnostics info (editing area)
#"diagnostic.warning" = { } # Diagnostics warning (editing area)
#"diagnostic.error" = { } # Diagnostics error (editing area)


# Gutter line
#"diff" = "white"
"diff.plus" = "green" # line added
"diff.minus" = "red" # removed lines
"diff.delta" = "yellow" # line modified
"diff.delta.moved" = "magenta" # line moved

"markup.normal.completion" = { } # for completion doc popup UI
"markup.normal.hover" = { } # for hover popup UI
"heading.completion" = { } # for completion doc popup UI
"heading.hover" = { } # for hover popup UI
"raw.inline.completion" = { } # for completion doc popup UI
"raw.inline.hover" = { } # for hover popup UI


"markup.heading" = "light-blue"
"markup.list" = "light-red"
"markup.bold" = { fg = "light-yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "light-magenta", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "yellow", modifiers = ["underlined"] }
"markup.link.text" = "light-red"
"markup.quote" = "light-cyan"
"markup.raw" = "light-green"


