[metadata]
aliases = []
author = 'chtenb'
name = 'Synthwave Material (neo-ansi)'

[colors]
foreground = "#cccccc"
background = "#262335"
cursor_bg = "#ffffff"
cursor_border = "#ffffff"
cursor_fg = "black"
selection_fg = "#cccccc"
selection_bg = "#333041"

ansi = ['#676e95' ,'#f07178' ,'#c3e88d' ,'#ffcb6b' ,'#94afeb' ,'#c792ea' ,'#b9dedf' ,'#b4b8d0']
brights = ['#676e95' ,'#ff5370' ,'#87de97' ,'#f78c6c' ,'#b9dedf' ,'#c792ea' ,'#91f5f8' ,'#dddddd']

[colors.indexed] 
52 = "#330f0f" # minus
88 = "#4f1917" # minus emph
22 = "#0e2f19" # plus
28 = "#174525" # plus emph
53 = "#330f29" # purple
17 = "#271344" # blue
23 = "#0d3531" # cyan
58 = "#222f14" # yellow

# bg
232 = "#2F2E43" # inactive background
233 = "#393850" # inactive overlay background
234 = "#42435E" # overlay background
235 = "#4B4E6C" # inactive overlay title bar
236 = "#54597A" # overlay title bar
237 = "#5E6387" # inactive main title bar
238 = "#241b30" # main title bar
239 = "#b0b0b0" # special highlight
240 = "#303030" # inactive selection
241 = "#404040" # active selection
242 = "#303030" # inactive primary selection
243 = "#4a3a48" # active primary selection
# fg
244 = "#444444" # Inactive inverse fg
245 = "#262335" # Soft inverse fg
246 = "#262335" # Regular inverse fg
247 = "#000000" # Highlighted inverse fg 
248 = "#909090" # 
249 = "#909090" # 
250 = "#7D83A4" # 
251 = "#9297B3" # 
252 = "#A8ACC2" # 
253 = "#BEC1D2" # 
254 = "#D4D6E1" # 
255 = "#E9EAF0" # 

# UI variants of base colors
226 = "#ffcb6b" # Yellow; warning

[colors.tab_bar]
background = "#241b30"
inactive_tab_edge = "#2F2E43"
inactive_tab_edge_hover = "#2F2E43"

[colors.tab_bar.active_tab]
bg_color = "#262335"
fg_color = "#cccccc"
# italic = false
# strikethrough = false
# underline = "None"
# intensity = "Normal"

[colors.tab_bar.inactive_tab]
bg_color = "#241b30"
fg_color = "#676e95"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#cccccc"
fg_color = "#676e95"

[colors.tab_bar.new_tab]
bg_color = "#241b30"
fg_color = "#676e95"

[colors.tab_bar.new_tab_hover]
bg_color = "#241b30"
fg_color = "#cccccc"
intensity = "Bold"
